#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $hour = 0;
my $minutes = 0;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

if ($acpi =~ /(\d\d):(\d\d):/) {
	$hour = $1 + 0;
	$minutes = $2;
}

if ($status eq 'Discharging' && $hour == 0 && $minutes < 20) {
	$full_text = '<span foreground="#ff0000"></span>  ';
} elsif ($status eq 'Discharging' && $percent >= 40) {
	$full_text = '<span foreground="#00aa00"></span>  ';
} elsif ($status eq 'Discharging' && $percent < 40) {
	$full_text = '<span foreground="#ffde00"></span>  ';
} elsif ($status eq 'Charging') {
	$full_text = '<span foreground="#00aa00"></span>  ';
} elsif ($status eq 'Full' or $percent >= 80) {
	$full_text = '<span foreground="#00aa00"></span> ';
} elsif ($percent >= 40) {
	$full_text = '<span foreground="#00aa00"></span> ';
} else {
	$full_text = '<span foreground="#ff0000"></span> ';
}
$full_text .= "$percent%";

$short_text = $full_text;

if ($hour > 0 || $minutes > 0) {
	$full_text .= " $hour:$minutes";
}

# print text
print "$full_text\n";
print "$short_text\n";

exit(0);
