#!/usr/bin/env python3
# coding=utf-8

# TODO is there a way to hide this block when external displays are on and the
# lid is closed?

import gi
from gi.repository import GObject
GObject.threads_init()

from dbus import glib
glib.init_threads()
import dbus
bus = dbus.SessionBus()

bright_obj = bus.get_object('org.gnome.SettingsDaemon.Power', '/org/gnome/SettingsDaemon/Power')
bright_props = dbus.Interface(bright_obj, 'org.gnome.SettingsDaemon.Power.Screen')

def show(*args, **kwargs):
    print("<span foreground=\"#00aa00\"></span> %i%%" % bright_props.GetPercentage())

show()

bus.add_signal_receiver(
    show,
    signal_name='Changed',
    dbus_interface='org.gnome.SettingsDaemon.Power.Screen'
)

loop = GObject.MainLoop()
loop.run()
