#!/usr/bin/env python3
# coding=utf-8

import time
import gi
from gi.repository import GObject
GObject.threads_init()

from dbus import glib
glib.init_threads()
import dbus
bus = dbus.SystemBus()

status = {
}

nm_obj = bus.get_object('org.freedesktop.NetworkManager', '/org/freedesktop/NetworkManager')
nm_props = dbus.Interface(nm_obj, dbus.PROPERTIES_IFACE)

state = nm_props.Get('org.freedesktop.NetworkManager', 'State')
if state == 60:  # connected, but no internet
    print("<span foreground=\"#ffde00\"> </span>")
elif state == 70:  # connected to all the things
    print("<span foreground=\"#00aa00\"> </span>")
else:  # no connectivity
    print("<span foreground=\"#ff0000\"> </span>")

connections = nm_props.Get('org.freedesktop.NetworkManager', 'ActiveConnections')
for connection in connections:
    obj = bus.get_object('org.freedesktop.NetworkManager', connection)
    connection_props = dbus.Interface(obj, dbus.PROPERTIES_IFACE)
    props = connection_props.GetAll('org.freedesktop.NetworkManager.Connection.Active')
    # if props['Default']:
    print(props['Default'])
    print(props['Type'])
    print(props['Devices'])

# print nm_props.Get('org.freedesktop.NetworkManager', 'Devices')


loop = GObject.MainLoop()
# loop.run()

# while True:
#     get_battery_info(upower)
#     format_output()
#     time.sleep(2)
