#!/bin/bash

if [[ -n $BLOCK_INSTANCE ]]; then
  INTERFACE=$BLOCK_INSTANCE
else
  INTERFACE=$(ip route | awk '/^default/ { print $5 ; exit }')
fi
STATE=$(cat /sys/class/net/$INTERFACE/operstate)

if [[ "$STATE" = "down" || "$INTERFACE" = "" ]]; then

  echo "<span foreground=\"#FF0000\">  </span>"
  echo "<span foreground=\"#FF0000\">  </span>"

elif [[ -e /sys/class/net/$INTERFACE/wireless ]]; then

  # INFO=$(/usr/bin/wicd-cli --wireless -d)
  INFO=$(/usr/bin/nmcli -t -f general,wifi-properties,ip4 device show $INTERFACE)

  while read line
  do
    case $line in
    IP4.ADDRESS*)
      IP="$(echo $line | cut -d':' -f 2 | cut -d'/' -f 1)"
      ;;
    GENERAL.CONNECTION*)
      ESSID="$(echo $line | cut -d':' -f 2)"
      ;;
    esac
  done <<< "$INFO"

  QUALITY="$(nmcli -t -f ssid,signal device wifi list | grep "^$ESSID:" | cut -d':' -f 2)"

  if [[ $QUALITY -le 50 ]]; then
    SYMBOL="<span foreground=\"#FFDE00\"> </span>"
  else
    SYMBOL="<span foreground=\"#00aa00\"> </span>"
  fi

  echo "$SYMBOL $ESSID  $IP"
  echo "$SYMBOL $ESSID"

else

  IP=$(/sbin/ifconfig $INTERFACE | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
  echo "<span foreground=\"#00aa00\"></span>  $IP"

fi
