#!/bin/bash

if [[ -n $BLOCK_INSTANCE ]]; then
  INTERFACE=$BLOCK_INSTANCE
else
  INTERFACE=$(ip route | awk '/^default/ { print $5 ; exit }')
fi
STATE=$(cat /sys/class/net/$INTERFACE/operstate)

if [[ "$STATE" = "down" || "$INTERFACE" = "" ]]; then

  echo "<span foreground=\"#FF0000\">  </span>"
  echo "<span foreground=\"#FF0000\">  </span>"

elif [[ -e /sys/class/net/$INTERFACE/wireless ]]; then

  INFO=$(/usr/bin/wicd-cli --wireless -d)

  while read line
  do
    case $line in
    IP*)
      set $line
      IP="$2"
      ;;
    Essid*)
      set $line
      ESSID="$2"
      ;;
    Quality*)
      set $line
      QUALITY="$2"
      ;;
    esac
  done <<< "$INFO"

  if [[ $QUALITY -le 50 ]]; then
    SYMBOL="<span foreground=\"#FFDE00\"> </span>"
  else
    SYMBOL=" "
  fi

  echo "$SYMBOL $ESSID  $IP"
  echo "$SYMBOL $ESSID"

else

  IP=$(/sbin/ifconfig $INTERFACE | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
  echo "  $IP"

fi
