#!/usr/bin/env python3
# coding=utf-8

from gi.repository import Wnck, Gtk, GObject
GObject.threads_init()

# */*': '*)
#   SYMBOL='' ;;

class WindowMonitor:

    def __init__(self):
        self.window_watcher = 0

        screen = Wnck.Screen.get_default()
        screen.force_update()
        self.get_title(screen)
        screen.connect('active-window-changed', self.get_title)

        loop = GObject.MainLoop()
        loop.run()

    def print_title(self, window):
        title = window.get_name()
        application = window.get_application().get_name()

        if application == 'Thunderbird':
            if title.endswith(' - Mozilla Thunderbird'):
                title = title[0:-22]
                icon = ''
            elif title.startswith('Write: '):
                icon = ''
        elif any(title.endswith(x) for x in [' - Gmail', ' - FreshGrade Mail']):
            icon = ''
        elif application == 'Signal':
            icon = ''
        elif title.startswith('Slack'):
            title = title[8:]
            icon = ''
        elif title.endswith('NVIM'):
            icon = ''
        elif application == 'Terminal':
            icon = ''

        elif title.endswith(' - Chromium'):
            title = title[0:-11]
            if 'YouTube' in title:
                icon = ''
            elif 'Kibana' in title:
                icon = ''
            elif 'Twitter' in title:
                icon = ''
            elif title.endswith(' - Google Search'):
                icon = ''
            elif title.endswith(' - Stack Overflow'):
                title = title [0:-17]
                icon = ''
            else:
                icon = ''
                # icon = ''

        # elif title.endswith(' - Mozilla Firefox'):
        #     title = title[0:-18]
        #     icon = ''

        elif 'JIRA' in title:
            icon = ''
        elif any(x in title for x in ['feedly', 'oskim', 'daily']):
            icon = ''
        elif title.endswith(' - Google Play Music'):
            title = title[0:-20]
            icon = ''
            # icon = ''
        elif 'Transmission Web Interface' in title:
            icon = ''
        elif any(x in title for x in ['Plex', 'Trakt']):
            icon = ''
        else:
            icon = ''

        if len(title) > 78:
            title = title[0:78]+' …'
        print('<span foreground="#00aa00"> '+icon+'</span><i> </i> ' + GObject.markup_escape_text(title) + ' ')

    def get_title(self, the_screen, prev_window=False):
        try:
            if self.window_watcher > 0 and 'disconnect' in dir(self.window):
                self.window.disconnect(self.window_watcher)
            self.window = the_screen.get_active_window()
            if 'connect' in dir(self.window):
                self.window_watcher = self.window.connect('name-changed', self.print_title)
                self.print_title(self.window)
            else:
                raise('No window')
        except Exception as e:
            # print(e)
            print('')


if __name__ == '__main__':
    WindowMonitor()

