#!/bin/bash

LASTTITLE=''
while true; do
  TITLE="$(xdotool getactivewindow getwindowname 2>/dev/null || echo 'None')"

  if [ "$TITLE" != "$LASTTITLE" ]; then
    case $TITLE in
      *Thunderbird|'Write: '*)
        SYMBOL='' ;;
      *Signal)
        SYMBOL='' ;;
      *Slack)
        SYMBOL='' ;;
      nathan@*)
        SYMBOL='' ;;
      */*': '*)
        SYMBOL='' ;;
      *' - YouTube - '*)
        SYMBOL='' ;;
      *'Plex'*)
        SYMBOL='' ;;
      *'Play Music')
        SYMBOL='' ;;
      *' - Gmail - '*|*' - FreshGrade Mail'|*' - Google Search - '*)
        SYMBOL='' ;;
      'daily - '*|'oskim - '*|daily|oskim)
        SYMBOL='' ;;
      *'Twitter - '*)
        SYMBOL='' ;;
      *' - Kibana - '*)
        SYMBOL='' ;;
      *'Transmission Web Interface'*)
        SYMBOL='' ;;
      *JIRA*)
        SYMBOL='' ;;
      *)
        SYMBOL='' ;;
    esac

    declare "LASTTITLE=$TITLE"
    # Cut window title down if it's too long
    if ((${#TITLE}>80))
      then TITLE="$(printf '%s …' "${TITLE:0:80}")"
    fi

    MYTITLE='<span foreground="#00aa00"> '$SYMBOL'<i> </i> <span foreground="#ffffff">'$(echo $TITLE | sed -e "s/&/&amp;/g")' </span></span>'

    echo $MYTITLE
  fi
  sleep 0.5
done

# …
#           
#   
# generic     
# email     
# chrome 
# firefox 
# music 
# signal 
# slack 
# youtube   
# github 
# google 
# terminal 
# feeds    
# twitter 
# 
